version: '3.3'

services:
  2bit-fe:
    image: rozanfa/
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    networks:
      - 2bit-network
    environment:
      - REACT_APP_BACKEND_URL=localhost:5000

  2bit-be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - /app/__pycache__
    networks:
      - 2bit-network

networks:
  2bit-network:
    driver: bridge
